### ISSUE TITLE
Multiple instance of Aura\View\Helper\Styles

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.View#13]
There are multiple instances of `Aura\View\Helper\Styles` and I feel not just styles but almost all , and finally the styles array becoming null `class Aura\View\Helper\Styles#266 (2) { protected $styles => array(0) { } protected $indent => string(4) " " }`

I was looking into the changes of the `config/default.php` https://github.com/auraphp/Aura.View/compare/master...develop#L2R30

**Comment by pmjones** [comment]
Sorry, I don't understand what the problem is here. Can you explain it a little more please?

**Comment by harikt** [comment]
You cannot do like this 

```
$this->scripts()->add('http://code.jquery.com/jquery-1.7.1.min.js');
$this->scripts()->add('/asset/Hari.Sample/js/bootstrap.min.js');

$this->styles()->add('/asset/Hari.Sample/css/bootstrap-responsive.min.css');
$this->styles()->add('/asset/Hari.Sample/css/bootstrap.css');

echo $this->metas()->get(); 
echo $this->title()->get();
echo $this->styles()->get();
```

This will not echo the results. You can try this from the sample https://github.com/harikt/Hari.Sample/blob/master/src/Hari/Sample/Web/Greet/layouts/default.php#L6

**Comment by pmjones** [comment]
I have written a temporary test in TemplateTest.php, like so:

```
public function testGithubIssue13()
{
    $template = $this->newTemplate();
    $helper_locator = $template->getHelperLocator();
    $helper_locator->set('metas', function() { return new \Aura\View\Helper\Metas; });
    $helper_locator->set('scripts', function() { return new \Aura\View\Helper\Scripts; });
    $helper_locator->set('styles', function() { return new \Aura\View\Helper\Styles; });
    $helper_locator->set('title', function() { return new \Aura\View\Helper\Title; });

    $template->scripts()->add('http://code.jquery.com/jquery-1.7.1.min.js');
    $template->scripts()->add('/asset/Hari.Sample/js/bootstrap.min.js');

    $template->styles()->add('/asset/Hari.Sample/css/bootstrap-responsive.min.css');
    $template->styles()->add('/asset/Hari.Sample/css/bootstrap.css');

    echo $template->metas()->get(); 
    echo $template->title()->get();
    echo $template->styles()->get();
}
```

It echoes the following:

```
<title></title>
<link rel="stylesheet" href="/asset/Hari.Sample/css/bootstrap.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/asset/Hari.Sample/css/bootstrap-responsive.min.css" type="text/css" media="screen" />
```

This appears to be the correct behavior. (Note that "scripts()->get()" is not called so it doesn't generate output.

What am I missing?

**Comment by pmjones** [comment]
Oh, oh, oh -- I think I see now. The problem is the config use of Lazy, instead of new instances via closures.  I will revert that particular change.
