### ISSUE TITLE
Error in Partial

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.View#16]
I have created a partial when playing with Aura.Framework in `develop` branch.

The view script it 

```
echo $this->fetch('code', [
    'controller_code' => $this->controller_code,
    'file_name' => 'hello',
]);
```

And in the partial I tried $controller_code and $file_name . It throws errors . So I changed to `$this->controller_code` . You can notice the `controller_code` is assigned from controller and it works as expected .  But the remaining fails.

```
<div>
    <p class="text-info">The Controller code that does this :) </p>
    <pre class="pre-scrollable"><?= $this->controller_code; ?></pre>
    <p class="text-info">The view <?= $this->file_name; ?></p>
</div>
```

**Comment by pmjones** [comment]
Try `echo $this->partial('code', [ ... ]);` instead of `$this->fetch()`.

**Comment by pmjones** [comment]
@harikt Is this still an issue?

**Comment by harikt** [comment]
what I did was `include $this->find('code');` and it worked. I have tested with partial now . 

And it also works.

Thanks
