### ISSUE TITLE
Aura View Helper not getting called :(

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.View#17]
Paul , 

I moved the view helper `SessionManager` from framework to `Hari.Sample` . I also have merged all the develop stuffs pushed. 

Now I am having a trouble . I am not able to get the `SessionManager` object. I feel its not calling invoke . Is it due to some changes in Aura.View ?

If you can please look into the https://github.com/harikt/Hari.Sample/blob/master/src/Hari/Sample/View/Helper/SessionManager.php

https://github.com/harikt/Hari.Sample/blob/master/config/default.php

to make the stuff not getting called from view

https://github.com/harikt/Hari.Sample/blob/master/src/Hari/Sample/Web/Post/views/add.php

It will be a great help if so.

Catchable fatal error: Object of class Hari\Sample\View\Helper\SessionManager could not be converted to string in /media/Linux/aurasystem/package/Hari.Sample/src/Hari/Sample/Web/Post/views/add.php on line 34 Call Stack: 0.0002 125932 1. {main}() /media/Linux/aurasystem/web/index.php:0 0.0006 155016 2. Aura\Framework\Bootstrap->execWeb() /media/Linux/aurasystem/web/index.php:11 0.0194 787772 3. Aura\Framework\Web\Controller\Front->exec() /media/Linux/aurasystem/package/Aura.Framework/src/Aura/Framework/Bootstrap.php:172 0.0195 788084 4. Aura\Framework\Web\Controller\Front->request() /media/Linux/aurasystem/package/Aura.Framework/src/Aura/Framework/Web/Controller/Front.php:154 0.0310 1251752 5. Aura\Web\Controller\AbstractPage->exec() /media/Linux/aurasystem/package/Aura.Framework/src/Aura/Framework/Web/Controller/Front.php:197 0.0320 1274300 6. Aura\Web\Controller\AbstractPage->render() /media/Linux/aurasystem/package/Aura.Web/src/Aura/Web/Controller/AbstractPage.php:135 0.0320 1274324 7. Aura\Framework\Web\Renderer\AuraViewTwoStep->exec() /media/Linux/aurasystem/package/Aura.Web/src/Aura/Web/Controller/AbstractPage.php:195 0.0324 1277180 8. Aura\View\TwoStep->render() /media/Linux/aurasystem/package/Aura.Framework/src/Aura/Framework/Web/Renderer/AuraViewTwoStep.php:135 0.0324 1278248 9. Aura\View\TwoStep->renderView() /media/Linux/aurasystem/package/Aura.View/src/Aura/View/TwoStep.php:454 0.0325 1278448 10. Aura\View\Template->fetch() /media/Linux/aurasystem/package/Aura.View/src/Aura/View/TwoStep.php:495 0.0327 1301956 11. require('/media/Linux/aurasystem/package/Hari.Sample/src/Hari/Sample/Web/Post/views/add.php') /media/Linux/aurasystem/package/Aura.View/src/Aura/View/Template.php:35

**Comment by harikt** [comment]
Fixed.

**Comment by pmjones** [comment]
What was the problem?

**Comment by harikt** [comment]
@pmjones You changed the `lazyNew()` to `newInstance()` . In my config it was having `lazyNew()` for those helpers. And it breaks. I am not sure whether it was injecting the dependencies. Wondering why so.

I changed back to 

```
$di->params['Aura\View\HelperLocator']['registry']['sessionManager'] = function () use ($di) {
    return $di->newInstance('Hari\Sample\View\Helper\SessionManager');
};
```
