### ISSUE TITLE
HTML attribute escaping (and JS, CSS, URL)

### ISSUE THREAD

**Issue by mattattui** [auraphp/Aura.View#19]
The current escaper class only performs HTML escaping, which limits its usefulness. I think it's worth adding `escapeHtmlAttr()` (and perhaps more, especially an `escapeJs()` for putting template variables into inline javascript). 

The BSD-licensed Zend Escaper class is an excellent reference for how to escape strings for JS and HTML attributes safely:  https://github.com/zendframework/zf2/blob/master/library/Zend/Escaper/Escaper.php

**Comment by pmjones** [comment]
Agreed. @harikt mentioned it a while back and I've been sitting on it since. I agree it would be a worthwhile addition. Thanks for the reminder.

**Comment by pmjones** [comment]
On review of the OWASP XSS prevention cheat sheet, it appears that HTML escaping is sufficient for _quoted_ attribute values.  As the attribs() helper always quotes attribute values, we don't seem to need additional escaping logic for them.  The others are a different story, and still bear review.

**Comment by pmjones** [comment]
We are going to resolve this more thoroughly in version 2, now under development.  Cf. the "develop-2" branch for more info.  (We are going back to manual escaping.)
