### ISSUE TITLE
My idea of Repeat Field

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.View#29]
Recently this was a problem I faced, probably it can be solved by some other way .

I have a `Add` button which can add as many fields. Let us say it is `title`, but it was really a group of fields.

When the user clicks on `Add` button I just added a `text` field with name as `fieldname[]` . This way I know the coming post value is an array for `POST['fieldname']` .

This helps me to see how many are there and what I need to insert . Also I need to do the validation part . What I can do is count the number of values and pass it and via for loop I added for the fields.

But the base idea when edit also comes was we may want to remove a field from the middle , and not at the bottom . So if we use something like `field1`, `field2`, `field3` etc , and say there are 10 fields. And I am going to remove the 5th and 7th one. 

We may will worry which went off. But on the other way I can just remove all and just re-insert  the values.

**Comment by pmjones** [comment]
We have a "repeat" field now; take a look and see if it suits your purposes.
