### ISSUE TITLE
Helpers methods chaining

### ISSUE THREAD

**Issue by ghost** [auraphp/Aura.View#36]
It would be nice if Helper's methods were chaining, like the Title helper, the append(), prepend() methods could return $this.

What do you think?

**Comment by harikt** [comment]
I feel it looks good.

```
$this->title()->set('View')->append(' Helper ')->prepend(' Aura
```

')->get()

_Hari K T_

http://harikt.com , https://github.com/auraphp

**Comment by ghost** [comment]
Hari,

Strange, I'm using PHP 5.4.15 and didn't worked.
Going to verify again.
I'm going to close the issue and if I find it again I open a new issue and post the stack trace.

Thanks!
