### ISSUE TITLE
Escaper Branch , inner view escaped twice?

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.View#4]
`render()` method calls `renderInnerView()` and `renderOuterView($inner)` . The `renderInnerView()` calls `setData()` and is escaped once.  Then the inner data contains the html data . Then `renderOuterView($inner)` again escapes the html also .

So I feel data will be escaped twice and the inner view html contents also escaped .

**Comment by pmjones** [comment]
The issue not about render(), etc.  It's about how the inner view is presented in the outer view (layout).  The layout needs to echo the __raw() inner view, so it doesn't get double-escaped.
