### ISSUE TITLE
Consistency accross Aura.Html and Aura.View

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.View#47]
Hi @pmjones ,

I noticed the name for escaping in Aura.Html is `safeHtml` , but in Aura.View , the `Helper\EscapeHtml` not added.

The name probably would be going as `escapeHtml` .

What are your thoughts on the same ?

**Comment by pmjones** [comment]
It's a good point. I have gone so far as to remove escaping from Aura.View v2 entirely, and leave it only in Aura.Html, partly as a result of this inconsistency. Thanks man.
