### ISSUE TITLE
Issue then using numeric key for options

### ISSUE THREAD

**Issue by dmolineus** [auraphp/Aura.View#48]
Same issue described for Aura.Html occurs when using Aura.View https://github.com/auraphp/Aura.Html/issues/6

Code line:
https://github.com/auraphp/Aura.View/blob/develop/src/Aura/View/Helper/Form/Select.php#L301

**Comment by harikt** [comment]
Aura.Html was born for v2 from Aura.View v1 you mentioned. 

That is why same behaviour. 

What do you think resolving this ?
Remove the hard typing ?

@pmjones working on a book and is busy http://mlaphp.com/ . He will get in touch hopefully tomorrow. see http://colabti.org/irclogger/irclogger_log/auraphp?date=2013-12-11#l19

**Comment by pmjones** [comment]
Won't fix this in Aura.View v1, but it has been fixed in Aura.Html v2 as of https://github.com/auraphp/Aura.Html/commit/936c9f40f47e13b09643ff32956f3f6afe0cfd05#diff-c68eba702590c26dced9e3e9667723ae
