### ISSUE TITLE
Possible bug with the aura closure view

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.View#54]
Hi Paul, 

I was just playing around to learn and implement ADR in aura. See https://github.com/harikt/adr/commit/f7f79e898d182c4fb9e0222044b9d1224e3498ad

In that I was writing a test on the render functionality done with aura/view. I am seeing something like 

``` php
PHPUnit 4.0.13 by Sebastian Bergmann.

Configuration read from /var/www/adr/tests/phpunit.xml

E.

Time: 30 ms, Memory: 3.75Mb

There was 1 error:

1) Aura\Action_Bundle\AuraViewTest::testRenderHello
Missing argument 1 for Aura\View\View::Aura\Action_Bundle\{closure}()

/var/www/adr/tests/src/AuraViewTest.php:17
/var/www/adr/vendor/aura/view/src/View.php:58
/var/www/adr/vendor/aura/view/src/View.php:58
/var/www/adr/vendor/aura/view/src/View.php:32
/var/www/adr/src/AuraView.php:24
/var/www/adr/tests/src/AuraViewTest.php:38

FAILURES!
Tests: 2, Assertions: 1, Errors: 1.
```

This sounds to me that there is some sort of bug in the View.

**Comment by pmjones** [comment]
Have you found out anything more about this?

**Comment by harikt** [comment]
nope. What I feel is about the closure being used inside another class makes the bind call on that particular class. That is a guess, not really something I found.

**Comment by pmjones** [comment]
It is true that each closure template has $this bound to the View instance.

**Comment by harikt** [comment]
So closures will not work the way expected makes it not usable.

**Comment by pmjones** [comment]
How is that not expected? Normally a closure _has_ no $this to begin with.

**Comment by harikt** [comment]
@pmjones I am wrong. I did a

``` php
$view_registry->set('hello', function ($name) {
    return "Hello {$name}";
});
```

Which was entirely wrong. May be the templates I created was old ones or may be via copy and paste got into it.

**Comment by harikt** [comment]
I copied from the tests https://github.com/auraphp/Aura.View/commit/2441295ed8d4d349290152cc7df6624db3f7059b . My bad.

**Comment by pmjones** [comment]
Ahh yes, I can see where that would be a problem. I should document that function params will not work with closures.
