### ISSUE TITLE
Solved: Static class and Template Closure problem

### ISSUE THREAD

**Issue by oytuntez** [auraphp/Aura.View#59]
Hi,

I'm using Aura.View in a class with static methods (read as Singleton). On set() method, I encountered a scoping problem, it would throw: "Cannot bind an instance to a static closure". 

Mentioned line would read: 

```
protected static function initializeView($name, $view) {
...
   return static::_getRegistry()->set('rawContent', function() use($content) {
       echo $content;
   });
...
}
```

It turned out the Closure was automatically taking `static` as its scope and this was problematic in AbstractView::getTemplate() method.

This is how I solved it out:

```
class RawContent {
    public function getClosure($view) {
        return function() use($view) {
            echo $view;
        };
    }
}
```

```
$closure = new RawContent();
return static::_getRegistry()->set('rawContent', $closure->getClosure($view));
```

Now our indirect closure in getClosure method will have a $this scope and not a static scope as the second part of the code has.

**Comment by pmjones** [comment]
Thanks for the information on this. I'm going to close the ticket, since it seems like you have solved the problem, but if you feel this needs added documentation, please send a pull request against the README.md file.  Thanks again!
