### ISSUE TITLE
May be an init method

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.View#63]
If Aura.View have an init method may be good to make use of it for people who need to do something after contruction. See https://github.com/pmjones/mvc-refinement/issues/17 . In the example I am trying to extend the `Aura\View\View` to set the layout and view.

**Comment by pmjones** [comment]
(/me ponders)

I think an init()-style method is best for something _outside_ the View package to have. The View is not in charge of initializing itself. E.g. the init() method would need some information passed into it so it would know _how_ to initialize itself, and that information is stored elsewhere in the project. Better to have a different class build up the View and return it.

**Comment by harikt** [comment]
@pmjones that way you have more classes for View . Tradeofffs ;) .

**Comment by pmjones** [comment]
yeah, tradeoffs :-)
