### ISSUE TITLE
Could you include a demo project/big picture in these repos?

### ISSUE THREAD

**Issue by jamesaspence** [auraphp/Aura.View#65]
When learning both aura.router and aura.view, it took me seeing somebody else's code before the entire picture clicked and I was able to understand how the libraries worked. Any chance you guys could include some sort of sample code in these repos? Maybe it's just me, but when just reading the instructions, I had trouble grasping exactly what was going on until I saw some tutorials detailing the entire process.

**Comment by harikt** [comment]
Hey @ThaPastafarian , 

May be we need some integration tutorials. I will try to make somethings like quick starts . Time and money is the culprit.

Thank you.

**Comment by jamesaspence** [comment]
Honestly that sample code you wrote up helped immensely, if nothing else maybe just include that in the repo as a sample? It gives a good idea of the structure/ how it all works.

**Comment by harikt** [comment]
Sure. We will think how to deal with this. Busy days :+1:  .

Thank you

**Comment by pmjones** [comment]
@harikt I know you have done some work on this lately. Can we include a link here and then close the issue?

**Comment by harikt** [comment]
Sure Paul.

General overview :

Aura version 1 view have been split into View and Html helpers. Aura.Html helpers are always useful when you are using Aura.View or Aura.Input or [extending another plates with aura helpers](http://harikt.com/blog/2014/05/13/extending-plates-with-aura-html-helpers/) . 

Different html helpers are documented over  https://github.com/auraphp/Aura.Html/blob/2.1.1/README-FORMS.md and https://github.com/auraphp/Aura.Html/blob/2.1.1/README-HELPERS.md  ( Switch to a different release and look into the docs ) .

If you are having trouble integrating Aura.View and Aura.Html  please look into 

https://github.com/harikt/AuraViewExample

Run composer install and look into the https://github.com/harikt/AuraViewExample/blob/master/view.php#L4-L10 how it is integrated. 

Hope that helps if not feel free to ask in google groups of auraphp.

Thanks
