### ISSUE TITLE
__construct() method, not __invoke() method, being called on helpers

### ISSUE THREAD

**Issue by ghost** [auraphp/Aura.View#67]
I am creating custom helpers, and registering them with the HelperRegistry. These  helpers are objects, and the object is instantiated using Aura.Di, thusly:

```
$di->params['Aura\View\HelperRegistry'] = [
    'map' => [
        'messages' => $di->lazyNew('Modus\Template\Helper\Messages'),
        'paginator' => $di->lazyNew('Modus\Template\Helper\Paginator'),
        'linkgenerator' => $di->lazyNew('Modus\Template\Helper\LinkGenerator'),
    ]
];
```

The problem is, when I use them in my views, the __construct() method is called, not the __invoke() method. Meaning that to call these methods, I must do the following:

```
<?php
$result = $this->linkgenerator();

echo $result('auth2');

?>
```

This isn't the way helpers used to work. The only way it seems to fix this issue is to create a closure, like so:

```
$di->params['Aura\View\HelperRegistry'] = [
    'map' => [
        'linkgenerator' => function($route) use ($di) {
            $obj = $di->newInstance('Modus\Template\Helper\LinkGenerator');
            return $obj($route);
        },
    ]
];
```

This is clearly sub-optimal. Also, there seems to be an issue whereby using $di->lazyNew() is a problem, as though lazyNew() itself is not callable.

**Comment by brandonsavage** [comment]
It appears that this is related to the way Aura.Di lazy-loads objects. Aura.Html assumes that all objects will be factories and invokes their construction, while the built-in helper locator here does not.

**Comment by harikt** [comment]
Hi @brandonsavagestealth , 

This is something similar to #66 . The https://github.com/auraphp/Aura.View/blob/develop-2/src/HelperRegistry.php#L38-L41 is array, but set is callable. So I believe the set should make use of the same functionality https://github.com/auraphp/Aura.View/blob/0a016a7d521db704e40041e693e39082c73e836f/src/TemplateRegistry.php#L63-L69 .

**Comment by harikt** [comment]
Will you be able to open a PR with the necessary changes ?

Thank you

**Comment by harikt** [comment]
This seems not possible in the current implementation. Please make use of the Aura.Html .

I thought of making the same hack as on https://github.com/auraphp/Aura.Html/blob/2.0.0/src/HelperLocator.php#L120-L125 . But it seems like the closure will be also called without an argument. So things will break. And the di itself will be a closure wrapped if I am correct.

So for the current time I recommend to make use of Aura.View + Aura.Html combined. You can make use of the bundle https://github.com/friendsofaura/FOA.Html_View_Bundle

**Comment by pmjones** [comment]
As you noticed, @brandonsavagestealth , the HelperRegistry expects fully-constructed objects, not factories or callables to create an object. If you are committed to HelperRegistry and Aura.Di, the solution is to avoid `lazyNew()` in favor of `newInstance()`:

```
$di->params['Aura\View\HelperRegistry'] = [
    'map' => [
        'messages' => $di->newInstance('Modus\Template\Helper\Messages'),
        'paginator' => $di->newInstance('Modus\Template\Helper\Paginator'),
        'linkgenerator' => $di->newInstance('Modus\Template\Helper\LinkGenerator'),
    ]
];
```

That has the drawback of creating the objects at config-time, rather than at the moment you call them. But then, that's what the HelperRegistry expects.

As @harikt mentioned, you may wish to review Aura.Html as an alternative, which _does_ support lazy-loading of helpers.

**Comment by pmjones** [comment]
Closing this per the solution in the above comment (i.e., use `newInstance()` instead of `lazyNew()`). If you feel this needs further attention please let me know.
