### ISSUE TITLE
DX : Bring TemplateFinder back to v2

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.View#69]
Hi Paul, 

When working on small projects I prefer to have a single `templates` folder. I could not comment for others but this seems to me a very lacking feature as I have already mentioned some time back. 

Before throwing an Exception do you think of looking for the template via TemplateFinder as we did in v1 
https://github.com/auraphp/Aura.View/blob/develop/src/Aura/View/TemplateFinder.php ?

Thank you

**Comment by pmjones** [comment]
If you want to bring TemplateFinder forward from v1, so that it matches the TemplateRegistry get/has methods, but searches the filesystem recursively like in v1, I'd be OK with that. Probably would need a new TemplateRegistryInterface with get/has.

**Comment by pmjones** [comment]
To be clear, this would be _in addition to_ the existing TemplateRegistry, not in replacement of.

**Comment by harikt** [comment]
Hi Paul,

I have made a PR https://github.com/auraphp/Aura.View/pull/70 .

Thank you for considering.

Not sure if I have made it correct as per your advice. Feel free to comment on the PR.
