### ISSUE TITLE
Mustache integration ?

### ISSUE THREAD

**Issue by ghost** [auraphp/Aura.View#76]
i want to ask wether this can be work with mustache ? https://github.com/bobthecow/mustache.php

**Comment by jakejohns** [comment]
Mustache appears to be it's own template engine, so I'm not sure why you would want to.
That being said, Aura\View templates are just PHP, so you could instantiate an instance if you wanted to, or even set an instance as a helper, but again, I'm not sure I see the point.

I think you might want to try asking for support on the mailing list, and also provide more context/information about what you're trying to accomplish.
