### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jakejohns** [auraphp/Aura.View#78]
https://github.com/auraphp/Aura.View/compare/2.2.1...2.x 

@harikt added a useful way to pass layout/view maps/paths to the `newInstance` method in  07548bf2f51e07f08347b1c8dd9d7c0b77ba3089 some time ago, but I dont believe theres a release yet.

**Comment by harikt** [comment]
Hi @jakejohns , 

Thank you for reminding me.

I have made a 2.3.0 release for Aura.View https://github.com/auraphp/Aura.View/releases/tag/2.3.0 .
