### ISSUE TITLE
unit test to vfsStream

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.View#8]
Try changing the unit tests to make use of https://github.com/mikey179/vfsStream .

So we don't need to worry about the file system and permissions of directory system.

**Comment by harikt** [comment]
vfsstream will not work with `getRealPath()`

https://github.com/mikey179/vfsStream/wiki/Known-Issues

Or we want to change the implementation at 

https://github.com/auraphp/Aura.View/blob/master/src/Aura/View/TemplateFinder.php#L198

to something like `is_readable($file)` .

But that doesn't fix everything.

More troubles like creating mockobject for `fetch()` .

To further proceed I need some help how to make this happen.

**Comment by pmjones** [comment]
We'll make this the very next priority, then. All the other packages seem OK now. :-)

**Comment by harikt** [comment]
great!

**Comment by harikt** [comment]
@pmjones we can get the file contents of vfsstream via 

`file_get_contents(vfsStream::url('root/tmp/foo/inner_view.php'))`

or via

`$this->root->getChild('tmp/foo/inner_view.php')->getContent()`

https://github.com/mikey179/vfsStream/issues/48#issuecomment-10488907

May be we need to change the fetch method to 

```
public function fetch($__name__)
{
    $file = $this->find($__name__);
    return file_get_contents($file);
}
```

or it seems a good idea to create a MockObject for the fetch method and return the content? I am not sure :( .

**Comment by pmjones** [comment]
Turned out that switching to "is_readable()" was the key, as you suggested @harikt . The change is made, the tests are converted to VfsStream, and life is good. :-)
